language: node_js
sudo: false
node_js:
- stable
deploy:
  provider: npm
  email: armsteadj1@gmail.com
  api_key: $NPM_API_KEY
  skip_cleanup: true
  on:
    tags: true
    repo: armsteadj1/react-plastic
